[tool.poetry]
name = "llmpeg"
version = "0.1.0"
description = "."
authors = ["rodfer0x80 <rodrigolf080@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
main = "llmpeg.__main__:main"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
tts = "^0.22.0"
bs4 = "^0.0.2"
yt-dlp = "^2024.4.9"
python-vlc = "^3.0.20123"
tiktoken = "^0.7.0"
ollama = "^0.2.0"
openai-whisper = "^20231117"
sounddevice = "^0.4.6"
soundfile = "^0.12.1"
nltk = "^3.8.1"
selenium = "^4.21.0"
easyocr = "^1.7.1"
jsonargparse = "^4.28.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
