indent-width = 2
line-length = 120

lint.select = [
  "F",
  "W6",
  "E71",
  "E72",
  #"E112",   # no-indented-block
  #"E113",   # unexpected-indentation
  # "E124",
  #"E203",   # whitespace-before-punctuation
  #"E272",   # multiple-spaces-before-keyword
  # "E303",
  # "E304",
  "E501",   # line-too-long
  # "E502",
  "E702",   # multiple-statements-on-one-line-semicolon
  "E703",   # useless-semicolon
  "E731",   # lambda-assignment
  "W191",   # tab-indentation
  "W291",   # trailing-whitespace
  "W293",   # blank-line-with-whitespace
  "UP039",  # unnecessary-class-parentheses
]

exclude = [
  "docs/",
  "examples/",
  "extra/",
  "scripts/",
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
# TODO: test if this is useful or necessary
# line-ending = "auto"

[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"**/{tests,docs,tools}/*" = ["E402"]
