class Triggers:
  audio_check = ["from", "by", "song", "music", "play"]
  audio_start = "play"
  goodbye = ["bye", "goodbye"]
  greeting = ["hi", "hello", "hey", "greetings"]
  goodbye_default_phrase = ["see", "you", "next", "time"]
  browse_check = ["search", "browse", "find", "lookup", "read about", "look up", "research", "explore", "investigate", "investigation", "study", "examine", "inspect", "scrutinize", "analyze"]
  browse_start = "browse"
  explain_check = ["explain", "and", "it", "the", "results", "what", "is", "about", "how", "why", "what"] + browse_check
  explain_start = "explain"
  summarize_check = ["summarize", "short", "brief", "and", "it", "the", "results", "how", "why", "abut", "what"] + browse_check
  summarize_start = "summarize"
  # weather_check = ["weather", "forecast", "temperature"]
  # weather_start = "weather"
  # news_check = ["news", "headlines", "articles"]
  # news_start = "news"
  # joke_check = ["joke", "funny", "humor"]
  # joke_start = "joke"
  # quote_check = ["quote", "inspire", "motivate"]
  # quote_start = "quote"
  # fact_check = ["fact", "interesting", "knowledge"]
  # fact_start = "fact"
  # trivia_check = ["trivia", "quiz", "question"]
  # trivia_start = "trivia"
  # riddle_check = ["riddle", "puzzle", "mystery"]
  # riddle_start = "riddle"
  # story_check = ["story", "tale", "narrative"]
  # story_start = "story"
  # poem_check = ["poem", "poetry", "verse"]
  # poem_start = "poem"
  # lyrics_check = ["lyrics", "song", "verse"]
  # lyrics_start = "lyrics"
  # movie_check = ["movie", "film", "cinema"]
  # movie_start = "movie"
  # series_check = ["series", "show", "episode"]
  # series_start = "series"
  # book_check = ["book", "novel", "literature"]
  # book_start = "book"
  # author_check = ["author", "writer", "creator"]
  # author_start = "author"
  # genre_check = ["genre", "type", "category"]
  # genre_start = "genre"
  # character_check = ["character", "person", "individual"]
  # character_start = "character"
  # plot_check = ["plot", "storyline", "narrative"]
  # plot_start = "plot"
  # setting_check = ["setting", "place", "location"]
  # setting_start = "setting"
  # theme_check = ["theme", "message", "moral"]
  # theme_start = "theme"
  # style_check = ["style", "technique", "method"]
  # style_start = "style"
  # language_check = ["language", "dialect", "accent"]
  # language_start = "language"
  # word_check = ["word", "term", "phrase"]
  # word_start = "word"
  # sentence_check = ["sentence", "phrase", "expression"]
  # sentence_start = "sentence"
  # paragraph_check = ["paragraph", "section", "passage"]
  # paragraph_start = "paragraph"
  # chapter_check = ["chapter", "section", "part"]
  # chapter_start = "chapter"
  # volume_check = ["volume", "book", "part"]
  # volume_start = "volume"
  # page_check = ["page", "sheet", "paper"]
  # page_start = "page"
  # line_check = ["line", "row", "queue"]
  # line_start = "line"
